version: 2.1

workflows:
  main:
    jobs:
      - sync-to-huggingface:
          context:
            - HuggingFace
          filters:
            branches:
              only:
                - main

jobs:
  sync-to-huggingface:
    docker:
      - image: alpine
    resource_class: small
    steps:
      - run: 
          name: install git
          command: apk update && apk add openssh-client git
      - checkout
      - run:
          name: push to Huggingface hub
          command: |
                  git config user.email "<chrs897@gmail.com>" 
                  git config user.name "<Aditya-NeuralNetNinja>" 
                  git push -f https://adi-123:${HUGGINGFACEHUB_API_TOKEN}@huggingface.co/spaces/adi-123/Image-to-Audio_Storyteller main
